version: '3'
services:
  ##################
  # Django Backend
  ##################
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
    - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - ./backend:/usr/src/backend-app
  ##################
  # React Frontend
  ##################
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    command: npm start
    ports:
    - 3001:3000
    environment:
    - CHOKIDAR_USEPOLLING=true
    volumes:
    - ./frontend:/usr/src/app
    - /usr/src/app/node_modules

