version: '3'
services:
  ##################
  # Django Backend
  ##################
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ./entrypoint.prod.sh
    env_file:
      -
    ports:
      - 8000:8000
    volumes:
      - ./backend:/usr/src/backend-app
    restart: always

  ##################
  # React Frontend
  ##################
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prebuilt
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - ./frontend/nginx:/etc/nginx/conf.d
      - ./frontend/certbot/conf:/etc/letsencrypt
      - ./frontend/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./frontend/certbot/conf:/etc/letsencrypt
      - ./frontend/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
