version: '3'
services:
  ##################
  # Django Backend
  ##################

#  backend:
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#    ports:
#      - 8000:8000
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - ./backend:/usr/src/backend-app

  ##################
  # React Frontend
  ##################
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - ./frontend/nginx:/etc/nginx/conf.d
      - ./frontend/certbot/conf:/etc/letsencrypt
      - ./frontend/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./frontend/certbot/conf:/etc/letsencrypt
      - ./frontend/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
